language: android
sudo: required
jdk: oraclejdk8

android:
  components:
    - tools
    - build-tools-26.0.2
    - android-26
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository
    - addon-google_apis-google-26
script:
    # Create two emulator avds.
  - echo no | android create avd --force -n test1 -t android-26 --abi armeabi-v7a
  
    # Start the first emulator.
  - emulator -avd test1 -no-skin -no-audio -no-window &
    # Wait for the first emulator to start.
  - sh scripts/wait-for-first-emulator.sh

    # Unlock the devices.
  - adb -s emulator-5554 shell input keyevent 82 &

    # Run the script.
  - sh scripts/script.sh
