language: android
sudo: required
jdk: oraclejdk8

android:
  components:
    - tools
    - tools # This is not a typo. Needed for SDK update.
    - platform-tools
    - android-24 
    - build-tools-24.0.1
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-22
script:
    # Create two emulator avds.
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  
    # Start the first emulator.
  - emulator -avd test -no-skin -no-audio -no-window &
    # Wait for the first emulator to start.
  - sh /wait-for-first-emulator.sh

    # Unlock the devices.
  - adb -s emulator-5554 shell input keyevent 82 &

    # Run the script.
  - sh /script.sh
