os: osx
osx_image: xcode9.2
language: objective-c
install:
  - nvm install node
  - brew update
  - brew cask install java
  - npm install -g appium
  - brew upgrade carthage
  - npm install -g ios-deploy
  - gem install xcpretty
  - npm install -g appium-doctor
  - npm install -g appium-xcuitest-driver
  - which java
  - which appium
before_script:
  - java -version
  - appium-doctor
  - find . -name 'appium-xcuitest-driver'
script:
  - cd pfizerappautomation/
